apiVersion: apps/v1
kind: Deployment
metadata:
  name: admissionform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admissionform
  template:
    metadata:
      labels:
        app: admissionform
    spec:
      containers:
      - name: app-container
        image: sowmya140/student-application-app:latest
        ports:
          - containerPort: 3028
        env:
         - name: MONGO_URI
           value: "mongodb://mongodb:27017/studentDB"
